apiVersion: v1
kind: Pod
metadata:
  name: elasticdl-test-mnist-master
  labels:
    app: elasticdl
    elasticdl-job-name: test-mnist
    elasticdl-replica-type: master
    elasticdl-replica-index: "0"
spec:
  containers:
  - name: mnist-demo-container
    image: elasticdl:ci
    command: ["/bin/bash"]
    args:
    - -c
    - >
      python -m elasticdl.python.master.main
      --model_zoo=model_zoo
      --model_def=mnist_functional_api.mnist_functional_api.custom_model
      --training_data_dir=/data/mnist/train
      --evaluation_data_dir=/data/mnist/test
      --num_epochs=2
      --grads_to_wait=10
      --minibatch_size=64
      --minibatches_per_task=2
      --num_workers=4
      --checkpoint_steps=10
      --evaluation_steps=15
      --worker_image=elasticdl:ci
      --job_name=test-mnist
      --log_level=INFO
      --image_pull_policy=Always
    imagePullPolicy: Always
    env:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: Never
