repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=79]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
-   repo: git://github.com/skorokithakis/pre-commit-mypy
    rev: v0.701
    hooks:
    - id: mypy
      args: [--ignore-missing-imports, --follow-imports=skip]
-   repo: local
    hooks:
    - id: clang-format
      name: clang-format
      description: Format files with ClangFormat.
      entry: bash ./scripts/codestyle/clang_format.hook -i
      language: system
      files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|proto)$
-   repo: local
    hooks:
    - id: cpplint-cpp-source
      name: cpplint
      description: Check C++ code style using cpplint.py.
      entry: bash ./scripts/codestyle/cpplint_precommit.hook
      language: system
      files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx)$

